version: "3.9"
name: trino

services:
  trino-coordinator:
    image: "trinodb/trino:428"
    ports:
      - '8080:8080'
    volumes:
      - ./trino/coordinator/etc:/etc/trino:ro
    depends_on:
      # - hive
      - trino-worker
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 3G

  trino-worker:
    image: "trinodb/trino:428"
    volumes:
      - ./trino/worker/etc:/etc/trino:ro
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 6G
  
  # coordinator:
  #   image: trinodb/trino:428
  #   hostname: coordinator
  #   networks:
  #     - default
  #   ports:
  #     - 8081:8080
  #     - 8445:8443
  #     - 9080:9080
  #     - 9081:9081
  #   volumes:
  #     - ./trino/config_coordinator:/etc/trino
    
  # worker:
  #   image: trinodb/trino:428
  #   networks:
  #     - default
  #   depends_on:
  #     - coordinator
  #   deploy:
  #     replicas: 2
  #   volumes:
  #     - ./trino/config_worker:/etc/trino

# networks:
#   default:
#     name: docker_network