version: '3'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
      POSTGRES_DB: hivemetastore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  hivemetastore:
    build:
      context: hive-metastorea
      dockerfile: Dockerfile
    # image: apache/hive-metastore:3.1.2
    environment:
      # POSTGRES_HOST: postgres
      # POSTGRES_PORT: 5432
      # POSTGRES_DB: hivemetastore
      # POSTGRES_USER: hive
      # POSTGRES_PASSWORD: hivepassword
      HIVE_METASTORE_MEMORY: 3G
      HIVE_METASTORE_DRIVER: "org.postgresql.Driver"
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hivepassword
      HIVE_METASTORE_JDBC_URL: "jdbc:postgresql://postgres:5432/hivemetastore"
      HIVE_METASTORE_MAX_POOL_SIZE: 35
      S3_PATH_STYLE_ACCESS: true
      # HIVE_METASTORE_SCHEMA_VERIFICATION: false
      # HIVE_METASTORE_INIT_SCHEMA_VERIFICATION: false
      # HIVE_METASTORE_CLIENT_CONNECT_RETRY_DELAY: 5
      # HIVE_METASTORE_CLIENT_CONNECT_RETRY_LIMIT: 10
    ports:
      - "9083:9083"
    deploy: 
      resources:
        limits:
          cpus: '0.5'
          memory: 5G
    depends_on:  
      postgres:
        condition: service_healthy
    
volumes:
  postgres-data:
