name: storage

services:
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - default
    entrypoint: sh
    volumes:
      - ./data:/data
    command:
      - -c
      - 'minio server /data --console-address :9001'
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
    driver: local

# networks:
#   default:
#     name: docker_network
