name: Docker Compose Validation
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate Docker Compose
        run: docker-compose config
      - name: Check validation result
        run: |
          if [ $? -eq 0 ]
          then
            echo "Docker Compose file is valid"
          else
            echo "Docker Compose file is invalid"
            exit 1
          fi
